export const GET_ERRORS = "GET_ERRORS";
export const GET_ACCOUNT_INFO = "GET_ACCOUNT_INFO";
export const USER_CREATED = "USER_CREATED";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_UPDATED = "USER_UPDATED";
export const RESERVATION_CREATED = "RESERVATION_CREATED";
export const RESERVATION_CANCELLED = "RESERVATION_CANCELLED";